font_size 12
font_family Hack Nerd Font
enable_audio_bell no
confirm_os_window_close 0
copy_on_select clipboard
map ctrl+shift+h launch --stdin-source=@screen_scrollback /opt/nvim/bin/nvim -u NONE -c "set nonumber norelativenumber clipboard=unnamedplus" -
