set -sg escape-time 5
set-option -g mode-keys vi 
set -g default-terminal "tmux-256color"
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi C-v send -X rectangle-toggle
bind -T copy-mode-vi y send -X copy-selection-and-cancel
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
